### ISSUE TITLE
Обратная связь

### ISSUE THREAD

**Issue by TheSmiley47** [gavvvr/hl2mp_ds#2]
Привет, я читал на форуме hl2dm.net что в году 2013 (может раньше) тебе J@nek скинул исходники AG2, если не трудно, не мог бы ты сделать репозиторий на гитхабе с сурсами дллок AG2, если они ещё у тебя сохранились? Был бы очень тебе благодарен. 
![1](https://user-images.githubusercontent.com/58108407/83111588-e6dddf80-a0d5-11ea-83db-b7b5ba53129d.PNG)

**Comment by gavvvr** [comment]
Привет. У меня никогда не было исходников AG2 и я не общался с J@nek (проверил свой e-mail)

Я спрашивал как-то у автора [hl2dm OB](https://www.moddb.com/mods/half-life-2-deathmatchob-beta-4), есть ли исходники на гитхабе. Он ответил, что нету
